### ISSUE TITLE
cgxsh: TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

### ISSUE THREAD

**Issue by libinjoseph88** [ebob9/cgxsh#3]
Hi Aaron,

It is not working on Python 3.10.0.

Error: -

cgxsh: TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

**Comment by prtg37** [comment]
Hi Aaron,

I'm getting the same error.

**Comment by ebob9** [comment]
This should now be fixed as of [v1.0.2](https://github.com/ebob9/cgxsh/releases/tag/v1.0.2), let me know if it is still broken!
